Add support for custom arguments
GatorEducator/SheetShuttle pull request #29
Opened 2022-02-01 23:03 UTC by tuduun

This pull request adds the ability to read a JSON file and pass the contents/arguments into a plugin. It also adds a command-line option to accept the file's path. 

closes #21

2022-02-02 03:03 UTC, noorbuchi requested changes

2022-02-02 03:03 UTC, noorbuchi commented on sheetshuttle/main.py
> +        return data
We should handle the error where the file does not exist and raise that error with a message. Please add that in a `try` statement

2022-02-03 23:02 UTC, antlet requested changes
Once the error handling is implemented like Noor mentioned, everything looks good to go and I will approve.

2022-02-21 03:09 UTC, noorbuchi commented
I ended up fixing some of the issues we discussed in addition to a bug that I remembered. Further testing is needed on some aspects but I think we can merge it for now. Can you please review this @antlet @tuduun @Yanqiao4396

2022-02-22 04:22 UTC, noorbuchi approved these changes

2022-02-22 15:50 UTC, antlet approved these changes
Looks good!

2022-02-22 15:58 UTC, merged