Restructure how sheets are accessed in the object oriented structure of the SheetCollector - Issue #41
GatorEducator/SheetShuttle pull request #44
Opened 2022-10-20 15:19 UTC by Makell-Logan

2022-10-24 21:00 UTC, noorbuchi commented
Please make sure that the build is passing. It looks like there are few issues where a variable is being used even though it's not defined.

2022-10-24 21:01 UTC, noorbuchi requested changes

2022-10-24 21:01 UTC, noorbuchi commented on sheetshuttle/sheet_collector.py
> +        for region_id, region in self.tabs[sheet[regions.items()]]:
what is `sheet` referring to here? This variable doesn't look to be defined in this scope

2022-11-10 16:49 UTC, EstebanMendez01 commented
New changes done for the enhancement to pass all the checks. All the tests are passing now. Please review @noorbuchi @jjumadinova

2022-11-10 16:50 UTC, EstebanMendez01 approved these changes, later dismissed

2022-11-10 16:51 UTC, Danniyb submitted a review, later dismissed

2022-11-10 16:53 UTC, tmiller-10 approved these changes, later dismissed

2022-11-10 20:21 UTC, noorbuchi requested changes

2022-11-10 20:21 UTC, noorbuchi commented on sheetshuttle/sheet_collector.py
> +# Changed some stuff in the plugin
Let's get rid of those unnecessary comments

2022-11-10 20:21 UTC, noorbuchi commented on sheetshuttle/sheet_collector.py
>          """Return a region object from the regions dictionary.
The documentation here needs to be revised to reflect what's being done

2022-11-10 20:21 UTC, noorbuchi commented on sheetshuttle/sheet_collector.py
> +        # New Approach
Let's not keep these comments here

2022-11-10 20:21 UTC, noorbuchi commented on sheetshuttle/sheet_collector.py
> +        # Fixed naming
Do we need these comments?

2022-11-10 20:21 UTC, noorbuchi commented on sheetshuttle/sheet_collector.py
> +        # Make a decision on the new file naming style
Do we need these comments?

2022-11-10 20:21 UTC, noorbuchi commented on sheetshuttle/sheet_collector.py
> +            # keep full_name, but use it just for opening the file
Do we need these comments?

2022-11-10 20:21 UTC, noorbuchi commented on sheetshuttle/sheet_collector.py
> +        # New Approach
Do we need these comments?

2022-11-10 21:23 UTC, EstebanMendez01 commented
Fixed comments and documentation errors

2022-11-12 00:28 UTC, noorbuchi submitted a review, later dismissed

2022-11-12 03:25 UTC, burgess01 approved these changes, later dismissed
This looks great- good job!

2022-11-15 19:05 UTC, noorbuchi approved these changes

2022-11-15 19:27 UTC, jjumadinova approved these changes
Looks good now. Thank you!

2022-11-15 19:31 UTC, merged